export const enum Puzzle {
  CalorieCounting = "calorie_counting",
  RockPaperScissors = "rock_paper_scissors",
  RucksackReorganization = "rucksack_reorganization",
  CampCleanup = "camp_cleanup",
  SupplyStacks = "supply_stacks",
  TuningTrouble = "tuning_trouble",
  NoSpaceLeftOnDevice = "no_space_left_on_device",
  TreetopTreeHouse = "treetop_tree_house",
  RopeBridge = "rope_bridge",
  CathodeRayTube = "cathode_ray_tube",
  MonkeyInTheMiddle = "monkey_in_the_middle",
  HillClimbingAlgorithm = "hill_climbing_algorithm",
  DistressSignal = "distress_signal",
  RegolithReservoir = "regolith_reservoir",
  BeaconExclusionZone = "beacon_exclusion_zone",
  ProboscideaVolcanium = "proboscidea_volcanium",
  PyroclasticFlow = "pyroclastic_flow",
  BoilingBoulders = "boiling_boulders",
}
